//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemesasEDM.ModeloApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteReceptor
    {
        public ClienteReceptor()
        {
            this.Envio = new HashSet<Envio>();
        }
    
        public int Id { get; set; }
        public string CodigoReceptor { get; set; }
        public string NombresReceptor { get; set; }
        public string Apellido1Receptor { get; set; }
        public string Apellido2Receptor { get; set; }
        public string DireccionReceptor { get; set; }
        public int TelefonoReceptor { get; set; }
        public string Cedula { get; set; }
        public int PaisId { get; set; }
    
        public virtual Pais Pais { get; set; }
        public virtual ICollection<Envio> Envio { get; set; }
    }
}
