//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemesasEDM.ModeloApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteEmisor
    {
        public ClienteEmisor()
        {
            this.Envio = new HashSet<Envio>();
        }
    
        public int Id { get; set; }
        public string CodigoEmisor { get; set; }
        public string NombresEmisor { get; set; }
        public string Apellido1Emisor { get; set; }
        public string Apellido2Emisor { get; set; }
        public string DireccionEmisor { get; set; }
        public int TelefonoEmisor { get; set; }
        public string Cedula { get; set; }
        public int PaisId { get; set; }
    
        public virtual Pais Pais { get; set; }
        public virtual ICollection<Envio> Envio { get; set; }
    }
}
