//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemesasEDM.ModeloApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envio
    {
        public Envio()
        {
            this.Notificaciones = new HashSet<Notificaciones>();
        }
    
        public int Id { get; set; }
        public string CodigoEnvio { get; set; }
        public double MontoPagado { get; set; }
        public System.DateTime FechaPago { get; set; }
        public int CodigoRetiro { get; set; }
        public int EstadoRemesaId { get; set; }
        public int ClienteEmisorId { get; set; }
        public int ClienteReceptorId { get; set; }
        public int TipoDeCambioId { get; set; }
    
        public virtual EstadoRemesa EstadoRemesa { get; set; }
        public virtual ICollection<Notificaciones> Notificaciones { get; set; }
        public virtual ClienteEmisor ClienteEmisor { get; set; }
        public virtual ClienteReceptor ClienteReceptor { get; set; }
        public virtual TipoDeCambio TipoDeCambio { get; set; }
    }
}
