//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemesasEDM.ModeloApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoRemesa
    {
        public EstadoRemesa()
        {
            this.Envio = new HashSet<Envio>();
        }
    
        public int Id { get; set; }
        public string CodigoEstadoRemesa { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<Envio> Envio { get; set; }
    }
}
