//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemesasEDM.ModeloApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDeCambio
    {
        public TipoDeCambio()
        {
            this.Envio = new HashSet<Envio>();
        }
    
        public int Id { get; set; }
        public string CodigoTipoCambio { get; set; }
        public double CambioDia { get; set; }
        public System.DateTime FechaTipoCambio { get; set; }
        public int MonedaId { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual ICollection<Envio> Envio { get; set; }
    }
}
